Var1:
  boundary_limits:
    high: 1.4698733974326457
    low: 0.6801266025673544
  drift_params:
    average: 1.075
    cusum_limit: 10
    cusum_minus: 0
    cusum_plus: 0
    cusum_threshold: 0.987183493581614
    ewma_alpha: 0.1
    ewma_smoothed: 0
  dynamic_threshold: 0.5
  frozen_threshold: 0.01
  statistic:
    data_size: 6
    iqr: 0.19250000000000012
    max: 1.3
    mean: 1.075
    median: 1.025
    min: 0.94
    oldest_value: 1.0
    quantile1: 0.97
    quantile3: 1.1625
    std: 0.14418737808837503
  tag_name: Var1
  tracking_size: 5
  type_to_check: &id001
    boundary: true
    drift: true
    dynamics: true
    frozen: true
Var2:
  boundary_limits:
    high: 13.36822878538309
    low: 6.965104547950242
  drift_params:
    average: 10.166666666666666
    cusum_limit: 10
    cusum_minus: 0
    cusum_plus: 0
    cusum_threshold: 8.00390529679106
    ewma_alpha: 0.1
    ewma_smoothed: 0
  dynamic_threshold: 0.5
  frozen_threshold: 0.01
  statistic:
    data_size: 6
    iqr: 1.5
    max: 12.0
    mean: 10.166666666666666
    median: 10.0
    min: 9.0
    oldest_value: 10.0
    quantile1: 9.25
    quantile3: 10.75
    std: 1.1690451944500122
  tag_name: Var2
  tracking_size: 5
  type_to_check: *id001
