Var1:
  boundary_limits: !!python/tuple
  - 8.623475382979798
  - -1.623475382979799
  drift_params:
    average: 3.5
    cusum_threshold: 12.808688457449499
    ewma_alpha: 0.1
  dynamic_threshold: 0.5
  frozen_threshold: 0.01
  tag_name: Var1
  tracking_size: 5
  type_to_check: &id001
    boundary: true
    drift: true
    dynamics: true
    frozen: true
Var2:
  boundary_limits: !!python/tuple
  - 13.36822878538309
  - 6.965104547950242
  drift_params:
    average: 10.166666666666666
    cusum_threshold: 8.00390529679106
    ewma_alpha: 0.1
  dynamic_threshold: 0.5
  frozen_threshold: 0.01
  tag_name: Var2
  tracking_size: 5
  type_to_check: *id001
